name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build tools/tools/tools.csproj
    - name: Generate
      run: dotnet run --project tools/tools/tools.csproj -- generate --content $GITHUB_WORKSPACE/content --templates $GITHUB_WORKSPACE/templates --output $GITHUB_WORKSPACE/output
